# Use a imagem base do Python 3.11
FROM python:3.11-slim

# Configurações do Python
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Definir diretório de trabalho
WORKDIR /app

# Instalar dependências do sistema
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Atualizar pip e ferramentas essenciais
RUN python -m pip install --upgrade pip setuptools wheel

# Copiar apenas o requirements.txt primeiro
COPY requirements.txt .

# Instalar dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o restante dos arquivos
COPY . .

# Expor a porta para acesso externo
EXPOSE 5000

# Rodar a aplicação
CMD ["python", "app.py"]
